"""
Joined-table inheritance: the `__subtypes__` branch of `CRUDRepository`.

Every write here has to walk the chain table by table - parent first on the way
in, child first on the way out - and every read has to come back as the schema
registered for the concrete type of the row, not for the base.
"""

import pytest
import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession

from src.core.exceptions import ModelNotFoundError
from src.core.schemas import PaginationSchema
from tests.integration.models import (
    Car,
    CarCreateSchema,
    CarReadSchema,
    CarUpdateSchema,
    Truck,
    TruckCreateSchema,
    TruckReadSchema,
    TruckUpdateSchema,
    Vehicle,
    VehicleCreateSchema,
    VehicleReadSchema,
    VehicleUpdateSchema,
    Widget,
    WidgetCreateSchema,
    WidgetUpdateSchema,
)
from tests.integration.repositories import VehicleRepository


async def count_rows(session: AsyncSession, table: sa.FromClause) -> int:
    statement = sa.select(sa.func.count()).select_from(table)
    return (await session.execute(statement)).scalar_one()


class TestCreate:
    async def test_creating_a_child_writes_one_row_per_table(
        self,
        vehicle_repo: VehicleRepository,
        session: AsyncSession,
        seed,
    ) -> None:
        """
        Joined-table inheritance means the parent INSERT and the child INSERT
        are two statements that must both land - and land exactly once.
        """
        vehicles_before = await count_rows(session, Vehicle.__table__)
        cars_before = await count_rows(session, Car.__table__)

        await vehicle_repo.create(CarCreateSchema(name="Hatchback", doors=5))

        assert await count_rows(session, Vehicle.__table__) == vehicles_before + 1
        assert await count_rows(session, Car.__table__) == cars_before + 1

    async def test_the_child_row_reuses_the_parent_generated_id(
        self,
        vehicle_repo: VehicleRepository,
        session: AsyncSession,
        seed,
    ) -> None:
        """
        The identity value is generated by the parent table and handed down: the
        child's `id` is a foreign key, so the two rows have to agree or the row
        is unreachable from either side.
        """
        result = await vehicle_repo.create(CarCreateSchema(name="Hatchback", doors=5))

        statement = sa.select(Car.__table__.c.id).where(
            Car.__table__.c.doors == 5,
        )
        assert (await session.execute(statement)).scalar_one() == result.id

    async def test_returns_the_schema_registered_for_the_child(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The repository is declared over `Vehicle`, but it dispatches on the
        create schema it was handed, so the result carries the child's columns.
        """
        result = await vehicle_repo.create(CarCreateSchema(name="Hatchback", doors=5))

        assert isinstance(result, CarReadSchema)
        assert (result.name, result.kind, result.doors) == ("Hatchback", "car", 5)

    async def test_creating_the_base_type_writes_only_the_base_table(
        self,
        vehicle_repo: VehicleRepository,
        session: AsyncSession,
        seed,
    ) -> None:
        """
        The base is a registered type in its own right; it must not pick up a
        child row on the way.
        """
        cars_before = await count_rows(session, Car.__table__)

        result = await vehicle_repo.create(VehicleCreateSchema(name="Plain"))

        assert isinstance(result, VehicleReadSchema)
        assert not isinstance(result, CarReadSchema)
        assert await count_rows(session, Car.__table__) == cars_before

    async def test_rejects_a_schema_that_was_never_registered(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        Dispatch is by exact schema type. An unregistered one has no table to go
        to, and saying so beats a `KeyError` from the mapping.
        """
        with pytest.raises(TypeError, match="WidgetCreateSchema"):
            # The wrong schema type is the point of the test, so mypy is
            # right to object - it is exactly what the guard catches.
            await vehicle_repo.create(
                WidgetCreateSchema(name="Wrong", slug="wrong", weight=1)  # type: ignore[arg-type]
            )


class TestBulkCreate:
    async def test_creates_several_subtypes_in_one_call(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The batching key is the model *and* the column set, so a mixed list is
        split into one INSERT chain per subtype - and still comes back in the
        order it was passed.
        """
        result = await vehicle_repo.bulk_create(
            [
                CarCreateSchema(name="Hatchback", doors=5),
                TruckCreateSchema(name="Pickup", payload_kg=1200),
                CarCreateSchema(name="Roadster", doors=2),
            ]
        )

        expected_types: list[type] = [CarReadSchema, TruckReadSchema, CarReadSchema]
        assert [type(schema) for schema in result] == expected_types
        assert [schema.name for schema in result] == ["Hatchback", "Pickup", "Roadster"]

    async def test_each_created_row_keeps_its_own_child_columns(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        Two subtypes in one call must not have their IDs or their child columns
        crossed while the batches are reassembled.
        """
        car, truck = await vehicle_repo.bulk_create(
            [
                CarCreateSchema(name="Hatchback", doors=5),
                TruckCreateSchema(name="Pickup", payload_kg=1200),
            ]
        )

        assert isinstance(car, CarReadSchema)
        assert isinstance(truck, TruckReadSchema)
        assert car.doors == 5
        assert truck.payload_kg == 1200
        assert car.id != truck.id


class TestRead:
    async def test_get_returns_the_schema_for_the_concrete_row_type(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        Asked through the base repository by ID alone, the row still comes back
        as the child schema: the mapper resolves the type from the discriminator
        and `read_schemas_mapping` follows it.
        """
        result = await vehicle_repo.get(seed.cars[0].id)

        assert isinstance(result, CarReadSchema)
        assert result.doors == seed.cars[0].doors

    async def test_get_all_mixes_the_base_and_its_subtypes(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        `selectin_polymorphic` is what pulls the child tables in, so a single
        `get_all` has to return each row as its own schema rather than flattening
        everything to the base.
        """
        result = await vehicle_repo.get_all(sorting=("id",))

        by_id = {schema.id: schema for schema in result}
        assert len(result) == len(seed.vehicles) + len(seed.cars) + len(seed.trucks)
        assert isinstance(by_id[seed.vehicles[0].id], VehicleReadSchema)
        assert isinstance(by_id[seed.cars[0].id], CarReadSchema)
        assert isinstance(by_id[seed.trucks[0].id], TruckReadSchema)

    async def test_get_all_loads_the_child_columns(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The child columns have to arrive with the read, not on a lazy attribute
        access: the ORM instance is gone by the time the caller has the schema.
        """
        result = await vehicle_repo.get_all()

        trucks = [schema for schema in result if isinstance(schema, TruckReadSchema)]
        assert [schema.payload_kg for schema in trucks] == [
            truck.payload_kg for truck in seed.trucks
        ]

    async def test_paginate_covers_the_whole_hierarchy(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The count is taken over the base table, which every subtype has a row
        in, so paging must not miss or double-count a child.
        """
        result = await vehicle_repo.paginate(
            PaginationSchema(limit=2, offset=0),
            sorting=("id",),
        )

        assert len(result.objects) == 2
        assert result.count == len(seed.vehicles) + len(seed.cars) + len(seed.trucks)


class TestUpdate:
    async def test_updates_a_column_that_lives_on_the_child(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        Only the child table has anything to write. The parent half of the
        statement ends up with an empty SET, which SQLAlchemy refuses - so the
        repository reads the parent row back instead of updating it.
        """
        car = seed.cars[0]

        result = await vehicle_repo.update(CarUpdateSchema(id=car.id, doors=3))

        assert isinstance(result, CarReadSchema)
        assert result.doors == 3
        assert result.name == car.name

    async def test_updates_a_column_that_lives_on_the_parent(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The other direction: the parent is updated and the child is only read
        back, and the result still has to carry both halves.
        """
        car = seed.cars[0]

        result = await vehicle_repo.update(CarUpdateSchema(id=car.id, name="Renamed"))

        assert isinstance(result, CarReadSchema)
        assert result.name == "Renamed"
        assert result.doors == car.doors

    async def test_updates_both_tables_at_once(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The ordinary case, and the one that proves the two statements are not
        exclusive.
        """
        car = seed.cars[0]

        result = await vehicle_repo.update(
            CarUpdateSchema(id=car.id, name="Renamed", doors=3)
        )

        assert isinstance(result, CarReadSchema)
        assert (result.name, result.doors) == ("Renamed", 3)

    async def test_the_change_is_visible_to_a_later_read(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        Both tables are written inside one savepoint, which is released as a
        unit.
        """
        car = seed.cars[0]

        await vehicle_repo.update(CarUpdateSchema(id=car.id, name="Renamed", doors=3))

        reread = await vehicle_repo.get(car.id)

        assert isinstance(reread, CarReadSchema)
        assert (reread.name, reread.doors) == ("Renamed", 3)

    async def test_raises_when_the_id_matches_nothing(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The parent is updated first, so a missing ID fails there before the
        child statement is ever built.
        """
        with pytest.raises(ModelNotFoundError):
            await vehicle_repo.update(CarUpdateSchema(id=10_000_000, doors=3))

    async def test_updating_through_the_base_schema_touches_only_the_base(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        `VehicleUpdateSchema` dispatches to `Vehicle`, so the child table is not
        even visited - and the result is the base schema, however the row was
        originally created.
        """
        car = seed.cars[0]

        result = await vehicle_repo.update(
            VehicleUpdateSchema(id=car.id, name="Renamed")
        )

        assert type(result) is VehicleReadSchema
        assert result.name == "Renamed"

    async def test_bulk_update_splits_by_subtype(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        Two subtypes in one call become separate executemany batches, each
        walking its own parent chain.
        """
        car, truck = seed.cars[0], seed.trucks[0]

        await vehicle_repo.bulk_update(
            [
                CarUpdateSchema(id=car.id, name="Renamed car", doors=3),
                TruckUpdateSchema(id=truck.id, payload_kg=9000),
            ]
        )

        updated_car = await vehicle_repo.get(car.id)
        updated_truck = await vehicle_repo.get(truck.id)

        assert isinstance(updated_car, CarReadSchema)
        assert isinstance(updated_truck, TruckReadSchema)
        assert (updated_car.name, updated_car.doors) == ("Renamed car", 3)
        assert (updated_truck.name, updated_truck.payload_kg) == (truck.name, 9000)


class TestUpsert:
    async def test_inserts_the_whole_chain_when_nothing_conflicts(
        self,
        vehicle_repo: VehicleRepository,
        session: AsyncSession,
        seed,
    ) -> None:
        """
        With no ID given there is nothing to conflict with, so the upsert walks
        the same parent-then-child path a create does.

        The conflict half cannot be reached here: making two calls collide takes
        an explicit ID, and `Vehicle` inherits `BaseInt`, whose key is
        `GENERATED ALWAYS` - Postgres rejects an INSERT that names it. That
        branch is covered on the UUID-keyed repository in `test_crud_write.py`.
        """
        cars_before = await count_rows(session, Car.__table__)

        result = await vehicle_repo.upsert(CarCreateSchema(name="Hatchback", doors=5))

        assert isinstance(result, CarReadSchema)
        assert (result.name, result.doors) == ("Hatchback", 5)
        assert await count_rows(session, Car.__table__) == cars_before + 1

    async def test_the_upserted_row_is_readable_as_its_subtype(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The discriminator has to be written along the way, or the row comes back
        as a bare `Vehicle`.
        """
        result = await vehicle_repo.upsert(CarCreateSchema(name="Hatchback", doors=5))

        assert isinstance(await vehicle_repo.get(result.id), CarReadSchema)


class TestDelete:
    async def test_removes_the_child_row_and_the_parent_row(
        self,
        vehicle_repo: VehicleRepository,
        session: AsyncSession,
        seed,
    ) -> None:
        """
        The child holds a foreign key to the parent, so the tables have to be
        emptied deepest first; the wrong order is a constraint violation, not a
        silent leftover.
        """
        car = seed.cars[0]

        await vehicle_repo.delete(car.id)

        assert await vehicle_repo.get_or_none(car.id) is None
        assert await count_rows(session, Car.__table__) == len(seed.cars) - 1
        assert await count_rows(session, Vehicle.__table__) == (
            len(seed.vehicles) + len(seed.cars) + len(seed.trucks) - 1
        )

    async def test_removes_several_subtypes_in_one_call(
        self,
        vehicle_repo: VehicleRepository,
        session: AsyncSession,
        seed,
    ) -> None:
        """
        The tables to visit are worked out from the discriminators the IDs
        actually point at, so a mixed list has to reach both child tables.
        """
        obj_ids = [seed.cars[0].id, seed.trucks[0].id]

        await vehicle_repo.bulk_delete(obj_ids)

        assert await count_rows(session, Car.__table__) == len(seed.cars) - 1
        assert await count_rows(session, Truck.__table__) == len(seed.trucks) - 1
        assert await vehicle_repo.get_multi(obj_ids) == []

    async def test_deleting_a_base_row_leaves_the_child_tables_alone(
        self,
        vehicle_repo: VehicleRepository,
        session: AsyncSession,
        seed,
    ) -> None:
        """
        An ID that points at a plain `Vehicle` resolves to the base table only;
        no child row shares it, and none may be removed.
        """
        await vehicle_repo.delete(seed.vehicles[0].id)

        assert await count_rows(session, Car.__table__) == len(seed.cars)
        assert await count_rows(session, Truck.__table__) == len(seed.trucks)

    async def test_raises_on_a_missing_id_when_strict(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The existence check runs against the base table before any table is
        touched.
        """
        with pytest.raises(ModelNotFoundError):
            await vehicle_repo.bulk_delete([10_000_000], strict=True)


class TestDispatchErrors:
    async def test_update_rejects_a_schema_that_was_never_registered(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        Same guard as on the create side, on the update mapping.
        """
        with pytest.raises(TypeError, match="WidgetUpdateSchema"):
            await vehicle_repo.update(
                WidgetUpdateSchema(id=seed.cars[0].id, name="X")  # type: ignore[arg-type]
            )

    async def test_read_rejects_a_model_with_no_registered_schema(
        self,
        vehicle_repo: VehicleRepository,
        seed,
    ) -> None:
        """
        The mirror of the guards above, on the read mapping: a row whose type
        nobody registered cannot be validated into anything, and the error has
        to name the `__subtypes__` entry that is missing.
        """
        unregistered = Widget(name="Unmapped", slug="unmapped", weight=1)

        with pytest.raises(TypeError, match="__subtypes__"):
            VehicleRepository.model_validate(unregistered)  # type: ignore[arg-type]
